version: '2'
services:
  php:
    image: tgsapache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps:/var/www/html
    links:
      - db

  db:
    image: tugasdb
    volumes:
     - ./db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=yuli